# Generated by Django 3.2.13 on 2022-05-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='My Name is Rishab Singh'),
            preserve_default=False,
        ),
    ]
